# Numpy Intro

In [1]:
import numpy as np

In [11]:
np.array([1,2,3,4])

array_a=np.array([6,7,8,9])

array_b=np.array([1.6,2.7,3.8,4.9])

array_c=np.array(["name","surname"])


In [7]:
print(array_a[0])
print(array_b[-2])
print(array_a[:2])

6
3.8
[6 7]


In [12]:
print(array_a.dtype)
print(array_b.dtype)
print(array_c.dtype)
#empty array data type becomes float

int32
float64
<U7


In [10]:
#we can data type transform
np.array([1,2,3,4], dtype=np.float_)

array([1., 2., 3., 4.])

#### Dimensions and Shapes

In [16]:
my_array=np.array([
    [1, 2, 3],
    [4, 5, 6]
])
#we can look at the dimensions
print(my_array.shape)

print(my_array.ndim)

print(my_array.size)

(2, 3)
2
6


In [18]:
dif_array=np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4],
        [3,2,1]
    ]

])

print(dif_array.shape)

print(dif_array.ndim)

print(dif_array.size)

(2, 2, 3)
3
12


#### Indexing and Slicing

In [32]:
new_array=np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(new_array[1])
print(new_array[1][2])
print(new_array[1,2])

#first row
print(new_array[0:2])
print(" ")
print(new_array[:2,:1])



[4 5 6]
6
6
[[1 2 3]
 [4 5 6]]
 
[[1]
 [4]]


In [33]:
new_array[1]=np.array([10,10,10])
print(new_array)
print(" ")
new_array[2]= 99
print(new_array)

[[ 1  2  3]
 [10 10 10]
 [ 7  8  9]]
 
[[ 1  2  3]
 [10 10 10]
 [99 99 99]]


In [48]:
print(np.arange(1,10,2))
array_d=np.arange(0,10)
print(array_d)


[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]


In [49]:
array_d.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [50]:
np.arange(1,10.1,4)

array([1., 5., 9.])

In [52]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
np.ones((2,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [54]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [64]:
r_array=np.random.random((4,3))
print(r_array)
print(" ")
r_int_array=np.random.randint(100,size=(4,3))
print(r_int_array)

[[0.89090472 0.29826935 0.99530834]
 [0.21251606 0.79953422 0.6487356 ]
 [0.87787532 0.54514276 0.19124272]
 [0.42272387 0.93645203 0.1509711 ]]
 
[[12 64 86]
 [78 82 56]
 [79 98 71]
 [16 23 56]]


In [66]:
#5 float numbers from 3 to 10
np.linspace(3,10,5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

Other methods: any(), all(), full(), concatenate()...

#### Statistics

In [75]:
array1=np.arange(1,10)
print(array1)

[1 2 3 4 5 6 7 8 9]


In [74]:
print(array1.sum())
print(array1.mean())
print(array1.std())
print(array1.var())

45
5.0
2.581988897471611
6.666666666666667


In [82]:
array1.sum(axis=0)

45

In [79]:
array1+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [84]:
array2=np.arange(0,10)
array2=array2.reshape(5,2)
print(array2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [85]:
array2+10

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

#### Boolean Arrays

In [87]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [89]:
a[0], a[-1]

(0, 3)

In [90]:
a>=2

array([False, False,  True,  True])

In [91]:
a[a>=2]

array([2, 3])

In [94]:
print(a.mean())
a[a>a.mean()]

1.5


array([2, 3])

In [95]:
a[~(a>a.mean())]

array([0, 1])

In [96]:
a[(a<=2) & (a%2==0)]

array([0, 2])

Questions                                                                                  
Create a 3x3 matrix of random integers up to 100.                                                 Filter those greater than 30 with boolean method                                                  

In [105]:
rnd=np.random.randint(100,size=(3,3))
print(rnd)
rnd[(rnd>=30)]


[[67 68 37]
 [18 84 17]
 [75 27 55]]


array([67, 68, 37, 84, 75, 55])

In [110]:
array_e=np.array([1,2,3,4,5,6,7,8,9,10])
array1=array_e.reshape(5,2)
array2=array_e.reshape(2,5)
print(array1)
print(" ")
print(array2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [111]:
np.dot(array1,array2)

array([[ 13,  16,  19,  22,  25],
       [ 27,  34,  41,  48,  55],
       [ 41,  52,  63,  74,  85],
       [ 55,  70,  85, 100, 115],
       [ 69,  88, 107, 126, 145]])

In [112]:
#Transpoze
array2.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [118]:
import sys
print(sys.getsizeof(10))
print(np.dtype(int).itemsize)
print(np.dtype(np.int8).itemsize)


28
4
1


In [121]:
my_list = list(range(100000))
my_array = np.arange(100000)
%time np.sum(my_array ** 2)

CPU times: total: 0 ns
Wall time: 1 ms


216474736

In [122]:
%time sum([number ** 2 for number in my_list])

CPU times: total: 0 ns
Wall time: 8.53 ms


333328333350000